sudo: required
dist: trusty
language: ruby
rvm:
    - 2.4.1
    - 2.4.2
    - 2.3.3
before_install:
    - sudo update-ca-certificates
install: bundle install
script: bash ./script/travis_build.sh
env:
    global:
        - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speed up isntallation

