# Dependencies
# markdown:         redcarpet
markdown: 	      kramdown 
highlighter:      rouge

# Permalinks
permalink:        /:year/:month/:title.html
# this has been deprecated in v3.0 relative_permalinks: true 

# Setup
title:            Shankar Kulumani 
tagline:          'PhD Candidate'
description:      'A personal site highlighting my research and interests.'
url:              "https://www.shankarkulumani.com"
enforce_ssl:      www.shankarkulumani.com 
baseurl:          /

author:
  name:           'Shankar Kulumani'
  url:            https://www.shankarkulumani.com
  twitter:        skulumani

paginate:         5

# Custom vars
version:          0.1
date:               "2017-12-13"

github:
  repo:           https://github.com/skulumani

repository: skulumani/skulumani.github.io
 
# Gems for Jekyll 
plugins:
  - 'jekyll-paginate'
  - 'jekyll-gist'
  - 'jekyll-seo-tag'
  - 'jekyll/scholar'

# Include hidden folder for keybase
include: [".well-known"]
exclude: [vendor, 'Gemfile', 'Gemfile.lock']

# Social media links
twitter_username:           skulumani
github_username:            skulumani
linkedin_username:          skulumani
academia_username:          ShankarKulumani
mendeley_username:          shankar-kulumani
orcid_username:             0000-0002-7822-0471
research_gate_username:     Shankar_Kulumani
google_scholar_username:    MOLoAf4AAAAJ
arxiv_username:             kulumani_s_1

# SEO Optimization
# SEO
twitter:
  username:           skulumani
  url:                https://twitter.com/skulumani
social:
  name:               Shankar Kulumani
  links:
    - https://linkedin.com/in/skulumani
    - https://github.com/skulumani
    - https://twitter.com/skulumani
    - https://plus.google.com/+ShankarKulumani
    - https://keybase.io/skulumani

# Jekyll-scholar settings
scholar:
  dependent/style: ieee
  locale: en

  sort_by: year
  order: descending

  # group_by: none
  # group_order: ascending

  source: ./_bibliography
  bibliography: references.bib
  bibliography_template: bibliography

  replace_strings: true
  # join_strings:    true

  # use_raw_bibtex_entry: true
  # bibtex_filters:
  # - superscript
  # - latex

  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details

  query: "@*"
