# Dependencies
# markdown:         redcarpet
markdown: 	      kramdown 
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Shankar Kulumani
tagline:          'Doctoral Student'
description:      'Doctoral Student'
url:              http://skulumani.github.io
baseurl:          /

author:
  name:           'Shankar Kulumani'
  url:            https://skulumani.github.io

paginate:         5

# Custom vars
version:          0.1

github:
  repo:           https://github.com/skulumani
