# Dependencies
# markdown:         redcarpet
markdown: 	      kramdown 
highlighter:      rouge

# Permalinks
permalink:        /:year/:month/:title
# this has been deprecated in v3.0 relative_permalinks: true 

# Setup
title:            Shankar Kulumani
tagline:          'PhD Candidate'
description:      'A personal site highlighting my research and interests.'
url:              https://skulumani.github.io
baseurl:          /

author:
  name:           'Shankar Kulumani'
  url:            https://skulumani.github.io

paginate:         5

# Custom vars
version:          0.1
date:			  "2016-10-26"

github:
  repo:           https://github.com/skulumani

repository: skulumani/skulumani.github.io
 
# Gems for Jekyll 
gems:             ['jekyll-paginate', 'jekyll-gist', 'jekyll-github-metadata']


# Include hidden folder for keybase
include: [".well-known"]

# Social media links
twitter_username:     skulumani
github_username:      skulumani
linkedin_username:    skulumani
google_plus_username: 
facebook_username:    
dribbble_username: