# Dependencies
# markdown:         redcarpet
markdown: 	      kramdown 
highlighter:      rouge

# Permalinks
permalink:        pretty
# this has been deprecated in v3.0 relative_permalinks: true 

# Setup
title:            Shankar Kulumani
tagline:          'Doctoral Candidate'
description:      'Doctoral Candidate'
url:              http://skulumani.github.io
baseurl:          /

author:
  name:           'Shankar Kulumani'
  url:            https://skulumani.github.io

paginate:         10

# Custom vars
version:          0.1
date:			  "2016-03-17"

github:
  repo:           https://github.com/skulumani
  
# Gems for Jekyll 
gems: [jekyll-paginate]
